<script lang="ts">
  import {onMount} from 'svelte'; import {apiGet,apiPost} from './api'; import Converter from './Converter.svelte';
  let recipes:any[]=[];let selected:any=null;let error='';let source='';let importing=false;
  async function refresh(){try{recipes=await apiGet('/recipes');}catch(e:any){error=e.message;}}
  async function add(){error='';try{await apiPost('/recipes',JSON.parse(source));source='';importing=false;await refresh();}catch(e:any){error=e.message;}}
  onMount(()=>void refresh());
</script>
{#if selected}<div class="platform"><button class="secondary" on:click={()=>selected=null}>Back to recipes</button></div><Converter recipe={selected}/>
{:else}<div class="platform"><h1>Container recipes</h1><p class="intro">Versioned deployment and maintenance recipes. Custom shell procedures run only when explicitly selected by an administrator. Live Proxmox acceptance remains pending.</p><button class="secondary" on:click={()=>importing=!importing}>Import recipe JSON</button>{#if error}<p class="error">{error}</p>{/if}{#if importing}<form class="panel" on:submit|preventDefault={add}><label>Recipe definition<textarea rows="14" bind:value={source} required spellcheck="false" placeholder={JSON.stringify({schema_version:1,id:'my-app',version:1,title:'My app',description:'Application',image:'myorg/app:1',health:{port:8080,http_path:'/health'},update:{mode:'image'}})}></textarea></label><p class="muted">Versions are immutable. Import a new version to change an existing recipe.</p><button>Import recipe</button></form>{/if}<div class="cards">{#each recipes as recipe}<div class="panel"><h2>{recipe.title} · v{recipe.version}</h2><p>{recipe.description}</p><code>{recipe.image}</code><p class="muted">{recipe.validation}</p><p>Update method: {recipe.update.mode}</p><button on:click={()=>selected={...recipe,hostname:recipe.id,port:recipe.health.port}}>Configure deployment</button></div>{/each}<div class="panel"><h2>Custom image</h2><p>Configure an OCI image and its persistent mounts.</p><button on:click={()=>selected={image:'',hostname:'',port:0,volumes:[]}}>Configure deployment</button></div></div></div>{/if}
