<script lang="ts">
  import {onMount,onDestroy} from 'svelte';import {apiGet,apiPost,apiPut} from './api';import {watchJob,type TaskEvent} from './jobs';
  let health:any[]=[];let recovery:any=null;let instances:any[]=[];let error='';let busy=false;let target='';let interval=0;let backupId='';let task='';let status='';let events:TaskEvent[]=[];let stopWatch:(()=>void)|undefined;
  async function action(fn:()=>Promise<void>){busy=true;error='';try{await fn();}catch(e:any){error=e.message;}finally{busy=false;}}
  async function refresh(){await action(async()=>{[health,recovery,instances]=await Promise.all([apiGet('/monitoring'),apiGet('/recovery'),apiGet('/databases')]);target=recovery.policy.target_instance_id||'';interval=recovery.policy.interval_hours;});}
  async function collect(){await action(async()=>{health=await apiPost('/monitoring/refresh',{});});}
  async function save(){await action(async()=>{await apiPut('/recovery/policy',{target_instance_id:target||null,interval_hours:interval});await refresh();});}
  async function verify(){await action(async()=>{const r=await apiPost('/databases/backups/'+backupId+'/verify',{target_instance_id:target});task=r.task_id;stopWatch?.();stopWatch=watchJob(task,(ev,s)=>{events=ev;status=s;if(['succeeded','failed','interrupted'].includes(s))void refresh();});});}
  onMount(()=>void refresh());onDestroy(()=>stopWatch?.());
</script>
<div class="platform"><h1>Health and recovery</h1><p class="intro">Check application readiness, capacity and backup history. A verified restore is stronger evidence than a successful dump.</p><button disabled={busy} on:click={refresh}>Refresh reports</button><button class="secondary" disabled={busy} on:click={collect}>Check live health</button>{#if error}<p class="error" role="alert">{error}</p>{/if}
<div class="cards">{#each health as report}<div class="panel"><h2>{report.name}</h2><p>{report.kind} · {report.status} · {report.application_health||''}</p><p class="muted">Observed {new Date(report.observed_at*1000).toLocaleString()}</p>{#if report.connections}<p>Connections: {report.connections.used}/{report.connections.max}</p>{/if}{#each report.backups||[] as b}<p>{b.name}: last backup {b.last_backup_at?new Date(b.last_backup_at*1000).toLocaleString():'none'}</p>{/each}{#each report.alerts||[] as a}<p class="error">{a}</p>{/each}{#if report.filesystem_usage}<details><summary>Mounted filesystem capacity</summary><pre>{report.filesystem_usage}</pre></details>{/if}{#if report.metrics}<details><summary>Resource metrics</summary><pre>{JSON.stringify(report.metrics,null,2)}</pre></details>{/if}</div>{/each}</div>
{#if recovery}<div class="panel"><h2>Database recovery</h2><p>Encryption: {recovery.encrypted_backups?'GPG recipient configured':'Not configured'}</p><p>Backup destination: <code>{recovery.backup_directory}</code></p>{#if !recovery.independent_destination_configured}<p class="error">Configure a separate mounted backup destination to survive loss of the manager disk.</p>{/if}<form on:submit|preventDefault={save}><div class="fields"><label>Verification instance<select bind:value={target}><option value="">Choose a separate instance</option>{#each instances.filter(i=>i.status==='ready') as i}<option value={i.id}>{i.name}</option>{/each}</select></label><label>Restore drill interval hours (0 disables)<input type="number" min="0" max="8760" bind:value={interval}/></label></div><p class="muted">Scheduled drills restore the latest backup per application into a separate instance, verify row counts, and remove only the generated verification database. Failed targets stay available for inspection.</p><button disabled={busy}>Save verification schedule</button></form><form on:submit|preventDefault={verify}><label>Backup ID<input required bind:value={backupId} placeholder="backup_..."/></label><button disabled={busy||!target}>Verify this backup now</button></form>
<h3>Restore drill results</h3>{#each recovery.verification as v}<p><code>{v.backup_id}</code> · {v.status} {v.finished_at?new Date(v.finished_at*1000).toLocaleString():''}</p>{#if v.error}<p class="error">{v.error}</p>{/if}{/each}<details><summary>Retained verification targets</summary><pre>{JSON.stringify(recovery.retained_targets,null,2)}</pre></details><p class="muted">{recovery.pitr}</p></div>{/if}
{#if task}<div class="panel"><h2>Verification: {status}</h2><pre>{events.map(e=>'['+e.step+'] '+e.message).join('\n')}</pre></div>{/if}</div>
