<script lang="ts">
  import { onMount,onDestroy } from 'svelte';
  import { apiGet,apiPost,apiPut } from './api';
  import { watchJob,type TaskEvent } from './jobs';
  let rows:any[]=[];let selected:any=null;let reports:any[]=[];let preview:any=null;let error='';let busy=false;let logs='';
  let applications:any[]=[];let database='';let image='';let method='image';let backupStorage='';let mode='image';let script='';let restart='';let interval=0;let timeout=900;let port=0;let httpPath='';let expected=200;
  let task='';let status='';let events:TaskEvent[]=[];let stopWatch:(()=>void)|undefined;
  async function perform(action:()=>Promise<void>){busy=true;error='';try{await action();}catch(e:any){error=e.message;}finally{busy=false;}}
  async function refresh(){await perform(async()=>{rows=await apiGet('/workloads');reports=await apiGet('/monitoring');const instances=await apiGet('/databases');applications=(await Promise.all(instances.filter((i:any)=>i.status==='ready').map((i:any)=>apiGet('/databases/'+i.id+'/apps')))).flat().filter((a:any)=>a.status==='ready');if(selected)selected=rows.find(w=>w.id===selected.id)||selected;});}
  function select(w:any){selected=w;preview=null;logs='';database='';image=w.active.image;backupStorage=w.update.backup_storage||'';mode=w.update.mode;script=w.update.script;restart=w.update.restart_script;interval=w.update.interval_hours;timeout=w.update.timeout_seconds;port=w.health.port||0;httpPath=w.health.http_path||'';expected=w.health.expected_status||200;}
  async function plan(){await perform(async()=>{preview=await apiPost('/workloads/'+selected.id+'/plan',{mode:method,image:image||null,backup_storage:backupStorage||null,database_id:database||null});});}
  function monitor(id:string){stopWatch?.();task=id;events=[];status='queued';stopWatch=watchJob(id,(ev,state)=>{events=ev;status=state;if(['succeeded','failed','interrupted','cancelled'].includes(state))void refresh();});}
  async function apply(){await perform(async()=>{const r=await apiPost('/workloads/'+selected.id+'/apply',{plan_id:preview.plan.id});preview=null;monitor(r.task_id);});}
  async function policy(){await perform(async()=>{selected=await apiPut('/workloads/'+selected.id+'/policy',{health:{port:port||null,http_path:httpPath||null,expected_status:httpPath?expected:null},update:{mode,script,restart_script:restart,timeout_seconds:timeout,interval_hours:interval,backup_storage:backupStorage||null}});preview=null;await refresh();});}
  async function showLogs(){await perform(async()=>{logs=(await apiGet('/workloads/'+selected.id+'/logs')).output;});}
  onMount(()=>void refresh());onDestroy(()=>stopWatch?.());
</script>
<div class="platform"><h1>Applications and updates</h1><p class="intro">OCI images run as unprivileged LXC containers. Replace the image with a new root disk, or use an explicit package/shell update policy for an application that supports it.</p>
<button disabled={busy} on:click={refresh}>Refresh</button>{#if error}<p class="error" role="alert">{error}</p>{/if}
<div class="cards">{#each rows as w}<div class="panel"><h2>{w.name}</h2><span class="badge">{w.status}</span><p>LXC {w.active.vmid} on {w.node} · {w.ip||'Address pending'}</p><code>{w.active.image||'OS template'}</code>{#if w.active.pinned_image}<p class="muted">{w.active.pinned_image}</p>{/if}{#each reports.find(r=>r.id===w.id)?.alerts||[] as alert}<p class="error">{alert}</p>{/each}<button class="secondary" on:click={()=>select(w)}>Manage updates</button></div>{/each}</div>{#if !rows.length}<p class="muted">New deployments appear here with their saved image and deployment specification. Older guests remain available in LXC Manager.</p>{/if}
{#if selected}<div class="panel"><h2>{selected.name}: update preview</h2>{#if selected.operation}<p class="error">Operation {selected.operation} must be resolved in Operation history before another update.</p>{/if}
<form on:submit|preventDefault={plan}><div class="fields"><label>Update method<select bind:value={method} on:change={()=>preview=null}><option value="image">Replace from an OCI image</option><option value="recipe">Run configured package/shell update</option><option value="rollback">Return to retained previous LXC</option><option value="refresh_credentials">Replace with fresh attached database credentials</option></select></label>{#if method==='image'}<label>Image tag or digest<input required bind:value={image} /></label>{/if}{#if method==='image'||method==='refresh_credentials'}<label>New database attachment (optional)<select bind:value={database}><option value="">Keep the existing attachment</option>{#each applications as a}<option value={a.id}>{a.name} / {a.username}</option>{/each}</select></label>{/if}<label>Proxmox backup storage<input bind:value={backupStorage} placeholder="Required when persistent volumes exist" /></label></div><button disabled={busy||!!selected.operation}>Build update preview</button></form>
{#if preview}<div class="panel"><h3>Ready to review</h3><p>Method: {preview.plan.mode}</p>{#if preview.plan.pinned_image}<code>{preview.plan.pinned_image}</code>{/if}<p>{preview.root_disk}</p><p>{preview.downtime}</p><p>{preview.rollback}</p>{#if preview.plan.mode==='recipe'}<p>Runs {preview.update.mode} inside LXC {selected.active.vmid}. A rollback snapshot is required. The update timeout is {preview.update.timeout_seconds} seconds.</p><pre>{preview.update.script}{'\n'}{preview.update.restart_script}</pre>{/if}<h4>Preserved mount paths</h4>{#each preview.volumes as v}<p>{v.container} · {v.storage||v.host}</p>{/each}{#if !preview.volumes.length}<p>No persistent mounts are declared.</p>{/if}<button disabled={busy} on:click={apply}>Apply reviewed update</button></div>{/if}
<h3>Retained revisions</h3>{#each selected.previous as r}<p>LXC {r.vmid} · {r.image} · {new Date(r.created_at*1000).toLocaleString()}</p>{/each}{#if !selected.previous.length}<p class="muted">No previous revision retained yet.</p>{/if}
<button class="secondary" disabled={busy} on:click={showLogs}>Read application logs</button>{#if logs}<pre>{logs}</pre>{/if}</div>
<form class="panel" on:submit|preventDefault={policy}><h2>Health and maintenance policy</h2><div class="fields"><label>Health TCP/HTTP port (0 disables)<input type="number" min="0" max="65535" bind:value={port} /></label><label>HTTP health path (optional)<input bind:value={httpPath} placeholder="/health" /></label><label>Expected HTTP status<input type="number" min="200" max="399" bind:value={expected} /></label><label>Update policy<select bind:value={mode}><option value="image">Image replacement</option><option value="apt">APT packages inside guest</option><option value="apk">APK packages inside guest</option><option value="shell">Application update script inside guest</option></select></label><label>Timeout seconds<input type="number" min="30" max="3600" bind:value={timeout}/></label><label>Automatic interval hours (0 disables)<input type="number" min="0" max="8760" bind:value={interval}/></label></div>
{#if mode==='shell'}<label>Administrator update script<textarea bind:value={script} required spellcheck="false" placeholder="/opt/application/bin/update --non-interactive"></textarea></label>{/if}{#if mode!=='image'}<label>Restart procedure after updating<textarea bind:value={restart} spellcheck="false" placeholder="systemctl restart hostable-app"></textarea></label><p class="muted">Guest commands require a node SSH key and pre-pinned host keys. Scripts execute inside this container as root. Automatic updates use this exact policy and a recovery snapshot.</p>{/if}<button disabled={busy||!!selected.operation}>Save policy</button></form>{/if}
{#if task}<div class="panel"><h2>Update: {status}</h2><code>{task}</code><pre>{events.map(e=>'['+e.step+'] '+e.message).join('\n')}</pre></div>{/if}</div>
